meta_product_name: "SkinClean"
meta_title: "SkinClean -Discrete, professional advice for your skin problems!"
meta_description: "Amazing website where you can get iscrete and professional advice for your skin problems! "
meta_image: "logo.png" # should exist in `app/assets/images/`
twitter_account: "@realDonaldTrump"   # required for Twitter Cards
